"use strict";
// This is auto-generated by Datastar. DO NOT EDIT.
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventTypes = exports.DefaultFragmentMergeMode = exports.FragmentMergeModes = exports.DatastarDatalineAutoRemove = exports.DatastarDatalineAttributes = exports.DatastarDatalineScript = exports.DatastarDatalinePaths = exports.DatastarDatalineOnlyIfMissing = exports.DatastarDatalineSignals = exports.DatastarDatalineUseViewTransition = exports.DatastarDatalineFragments = exports.DatastarDatalineSettleDuration = exports.DatastarDatalineMergeMode = exports.DatastarDatalineSelector = exports.DefaultExecuteScriptAutoRemove = exports.DefaultMergeSignalsOnlyIfMissing = exports.DefaultFragmentsUseViewTransitions = exports.DefaultExecuteScriptAttributes = exports.DefaultSseRetryDurationMs = exports.DefaultFragmentsSettleDurationMs = exports.VERSION = exports.DATASTAR_REQUEST = exports.DATASTAR = void 0;
exports.DATASTAR = "datastar";
exports.DATASTAR_REQUEST = "Datastar-Request";
exports.VERSION = "1.0.0-beta.7";
// #region Defaults
// #region Default durations
// The default duration for settling during fragment merges. Allows for CSS transitions to complete.
exports.DefaultFragmentsSettleDurationMs = 300;
// The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
exports.DefaultSseRetryDurationMs = 1000;
// #endregion
// #region Default strings
// The default attributes for <script/> element use when executing scripts. It is a set of key-value pairs delimited by a newline \\n character.
exports.DefaultExecuteScriptAttributes = "type module";
// #endregion
// #region Default booleans
// Should fragments be merged using the ViewTransition API?
exports.DefaultFragmentsUseViewTransitions = false;
// Should a given set of signals merge if they are missing?
exports.DefaultMergeSignalsOnlyIfMissing = false;
// Should script element remove itself after execution?
exports.DefaultExecuteScriptAutoRemove = true;
// #endregion
// #region Datalines
exports.DatastarDatalineSelector = "selector";
exports.DatastarDatalineMergeMode = "mergeMode";
exports.DatastarDatalineSettleDuration = "settleDuration";
exports.DatastarDatalineFragments = "fragments";
exports.DatastarDatalineUseViewTransition = "useViewTransition";
exports.DatastarDatalineSignals = "signals";
exports.DatastarDatalineOnlyIfMissing = "onlyIfMissing";
exports.DatastarDatalinePaths = "paths";
exports.DatastarDatalineScript = "script";
exports.DatastarDatalineAttributes = "attributes";
exports.DatastarDatalineAutoRemove = "autoRemove";
// #endregion
// #region Enums
// The mode in which a fragment is merged into the DOM.
exports.FragmentMergeModes = [
    // Morphs the fragment into the existing element using idiomorph.
    "morph",
    // Replaces the inner HTML of the existing element.
    "inner",
    // Replaces the outer HTML of the existing element.
    "outer",
    // Prepends the fragment to the existing element.
    "prepend",
    // Appends the fragment to the existing element.
    "append",
    // Inserts the fragment before the existing element.
    "before",
    // Inserts the fragment after the existing element.
    "after",
    // Upserts the attributes of the existing element.
    "upsertAttributes",
];
// Default value for FragmentMergeMode
exports.DefaultFragmentMergeMode = "morph";
// The type protocol on top of SSE which allows for core pushed based communication between the server and the client.
exports.EventTypes = [
    // An event for merging HTML fragments into the DOM.
    "datastar-merge-fragments",
    // An event for merging signals.
    "datastar-merge-signals",
    // An event for removing HTML fragments from the DOM.
    "datastar-remove-fragments",
    // An event for removing signals.
    "datastar-remove-signals",
    // An event for executing <script/> elements in the browser.
    "datastar-execute-script",
];
// #endregion
// #endregion
